routes/admin.php
<?php
	
//Rutas para peliculas
Route::resource('movie','MovieController');
Route::post('movie/store', ['as' => 'movie/store', 'uses' => 'MovieController@store']);
Route::get('movie/destroy/{id}', ['as' => 'movie/destroy', 'uses' => 'MovieController@destroy']);
Route::put('movie/update', ['as' => 'movie/update', 'uses' => 'MovieController@update']);
Route::post('movie/search', ['as' => 'movie/search', 'uses' => 'MovieController@search']);

// Rutas para categorias
Route::resource('category','CategoryController');
Route::get('category/destroy/{id}', ['as' => 'category/destroy', 'uses' => 'CategoryController@destroy']);
Route::post('category/show', ['as' => 'category/show', 'uses' => 'CategoryController@show']);
Route::post('category/store', ['as' => 'category/store', 'uses' => 'CategoryController@store']);
Route::put('category/update', ['as' => 'category/update', 'uses' => 'CategoryController@update']);
Route::post('category/search', ['as' => 'category/search', 'uses' => 'CategoryController@search']);

// Rutas para Usuarios
Route::resource('user','UserController');
Route::get('user/destroy/{id}', ['as' => 'user/destroy', 'uses' => 'UserController@destroy']);
Route::post('user/search', ['as' => 'user/search', 'uses' => 'UserController@search']);

// Rutas para Estados
Route::resource('state','StateController');
Route::get('state/destroy/{id}', ['as' => 'state/destroy', 'uses' => 'StateController@destroy']);
Route::post('state/search', ['as' => 'state/search', 'uses' => 'StateController@search']);

// Rutas para Excel "Carga masiva"
Route::post('/import-excel', ['as'=> 'import-excel', 'uses' => 'ExcelController@importMovies']);

?>

routes/user.php
<?php

//Rutas para peliculas
Route::get('movieList', ['as' => 'movieList', 'uses' => 'MovieController@list']);
?>

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/movies/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-12">
				{!! Form::open(['route' => 'movie/search', 'method' => 'post', 'novalidate', 'class' => 'form-inline']) !!}
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" class="form-control" name="name">
					</div>
					<div class="form-control">
						<button type="submit" class="btn btn-default">Buscar</button>
						<a href="{{ route('movie.index') }}" class="btn btn-primary">Todo</a>
						<a href="{{ route('movie.create') }}" class="btn btn-primary">Crear</a>						
					</div>	
				{!! Form::close() !!}
			</article>
			<article class="col-md-12">
				<table class="table table-condensed table-striped table-bordered">
					<thead>
						<tr>
							<th>Nombre</th>
							<th>Descripción</th>
							<th>Estado</th>
							<th>Categorias</th>
							<th>Usuario</th>
							<th>Acción</th>
						</tr>
					</thead>
					<tbody>
						@foreach($movies as $movie)
							<tr>
								<td>{{ $movie->name }}</td>
								<td>{{ $movie->description }}</td>
								<td>{{ $movie->state->state }}</td>
								<td>
									@foreach($movie->categories as $movieCategory)
										{{ $movieCategory->name }}
									@endforeach
								</td>
								<td>{{ $movie->user->name }}</td>
								<td>
									<a class="btn btn-primary btn-xs" href="{{ route('movie.edit',['id' => $movie->id]) }}">Editar</a>
									<a class="btn btn-danger btn-xs" href="{{ route('movie/destroy',['id' => $movie->id]) }}">Eliminar</a>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</article>
		</div>
	</section>
@endsection

resources/views/movies/listMovies.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-12">
				{!! Form::open(['route' => 'movie/search', 'method' => 'post', 'novalidate', 'class' => 'form-inline']) !!}
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" class="form-control" name="name">
					</div>
					<div class="form-control">
						<button type="submit" class="btn btn-default">Buscar</button>					
					</div>	
				{!! Form::close() !!}
			</article>
			<article class="col-md-12">
				<table class="table table-condensed table-striped table-bordered">
					<thead>
						<tr>
							<th>Nombre</th>
							<th>Descripción</th>
						</tr>
					</thead>
					<tbody>
						@foreach($movies as $movie)
							<tr>
								<td>{{ $movie->name }}</td>
								<td>{{ $movie->description }}</td>
								<td>
									@foreach($movie->categories as $movieCategory)
										{{ $movieCategory->name }}
									@endforeach
								</td>	
							</tr>
						@endforeach
					</tbody>
				</table>
			</article>
		</div>
	</section>
@endsection

resources/views/movies/new.blade.php
@extends('layouts.app')
@section('content')
	<new-movie :edit="false" :movie="null" :states="null"></new-movie>
	<section>
    <div class="links">
    <form method="post" action="{{url('import-excel')}}" enctype="multipart/form-data">
        {{csrf_field()}}
        <input type="file" name="excel">
        <br><br>
        <input type="submit" value="Enviar" style="padding: 10px 20px;">
    </form>
  </div>
  </section>
@endsection

resources/views/movies/update.blade.php
@extends('layouts.app')
@section('content')
	<new-movie :edit="true" :movie="{{$movie}}" :states="{{$states}}"></new-movie>
@endsection