routes/admin.php
<?php
	
//Rutas para peliculas
Route::resource('movie','MovieController');
Route::post('movie/store', ['as' => 'movie/store', 'uses' => 'MovieController@store']);
Route::get('movie/destroy/{id}', ['as' => 'movie/destroy', 'uses' => 'MovieController@destroy']);
Route::put('movie/update', ['as' => 'movie/update', 'uses' => 'MovieController@update']);
Route::post('movie/search', ['as' => 'movie/search', 'uses' => 'MovieController@search']);

// Rutas para categorias
Route::resource('category','CategoryController');
Route::get('category/destroy/{id}', ['as' => 'category/destroy', 'uses' => 'CategoryController@destroy']);
Route::post('category/show', ['as' => 'category/show', 'uses' => 'CategoryController@show']);
Route::post('category/store', ['as' => 'category/store', 'uses' => 'CategoryController@store']);
Route::put('category/update', ['as' => 'category/update', 'uses' => 'CategoryController@update']);
Route::post('category/search', ['as' => 'category/search', 'uses' => 'CategoryController@search']);

// Rutas para Usuarios
Route::resource('user','UserController');
Route::get('user/destroy/{id}', ['as' => 'user/destroy', 'uses' => 'UserController@destroy']);
Route::post('user/search', ['as' => 'user/search', 'uses' => 'UserController@search']);

// Rutas para Estados
Route::resource('state','StateController');
Route::get('state/destroy/{id}', ['as' => 'state/destroy', 'uses' => 'StateController@destroy']);
Route::post('state/search', ['as' => 'state/search', 'uses' => 'StateController@search']);

// Rutas para Excel "Carga masiva"
Route::post('/import-excel', ['as'=> 'import-excel', 'uses' => 'ExcelController@importMovies']);

?>

routes/user.php
<?php

//Rutas para peliculas
Route::get('movieList', ['as' => 'movieList', 'uses' => 'MovieController@list']);
?>

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','state_id','role'
    ];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $guarded = ['status'];

    public function state()
    {
        return $this->belongsTo('App\Models\State');
    }

    public function movies(){
        return $this->hasMany('App\Models\Movie');
    }
    
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\User;
class UserController extends Controller
{
    public function index(){
    	$users = User::all();
    	return \View::make('users/list',compact('users'));
    }

     public function search(Request $request){
        $users = User::where('name','like','%'.$request->name.'%')->get(); //busca por nombre similar
        //$users = User::where('name','=',$request->name)->get();//busca por nombre igual
        return \View::make('users/list',compact('users'));
    }

    public function edit($id){
    	$user = User::find($id);
        $states = DB::table('states')->get();
    	return \View::make('users/update', compact('user'),compact('states'));
    }

    public 	function update($id, Request $request){
    	$user = User::find($id);
    	$user->name = $request->name;
    	$user->email = $request->email;
        $user->role = $request->role;
        $user->state_id = $request->state;
    	$user->save();
    	return redirect('user');
    }

}

resources/views/users/list.blade.php
@extends('layouts.app')
@section('content')
		<section class="container">
		<div class="row">
			<article class="col-md-12">
				{!! Form::open(['route' => 'user/search', 'method' => 'post', 'novalidate', 'class' => 'form-inline']) !!}
					<div class="form-group">
						<label>Nombre de usuario</label>
						<input type="text" class="form-control" name="name">
					</div>
					<div >
						<button type="submit" class="btn btn-default">Buscar</button>
						<a href="{{ route('user.index') }}" class="btn btn-primary">Todo</a>
					</div>	
				{!! Form::close() !!}
			</article>
			<article class="col-md-12">
				<table class="table table-condensed table-striped table-bordered">
					<thead>
						<tr>
							<th>Nombre</th>
							<th>E-mail</th>
							<th>Estado</th>
							<th>Acción</th>
						</tr>
					</thead>
					<tbody>
						@foreach($users as $user)
							<tr>
								<td>{{ $user->name }}</td>
								<td>{{ $user->email }}</td>
								<td>{{ $user->state->state }}</td>
								<td>
									<a class="btn btn-primary btn-xs" href="{{ route('user.edit',['id' => $user->id]) }}">Editar</a>
								</td>
							</tr>		
						@endforeach
					</tbody>
				</table>
			</article>
		</div>
	</section>
@endsection

resources/views/users/update.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!! Form::model($user,['route' => ['user.update', $user->id], 'method' => 'put', 'novalidate']) !!}
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" name="name" class="form-control" required value="{{ $user->name }}">
					</div>
					<div class="form-group">
						<label>E-mail</label>
						<input type="text" name="email" class="form-control" required value="{{ $user->email }}">
					</div>
					<div class="=form-group">	
						<p>Estado actual</p>
						<p>{{$user->state->state}}</p>
					</div>
					<div class="form-group">
						<select name="state" class="form-control">
							@forelse($states as $state)
	    						<option value="{{$state->id}}" >{{ $state->state }}</option>
							@empty
	    						<option>No hay estados registrados.</option>
							@endforelse
						</select>
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-success">Enviar</button>
					</div>
				{!! Form::close() !!}
			</article>
		</div>	
	</section>
@endsection