routes/admin.php
<?php
	
//Rutas para peliculas
Route::resource('movie','MovieController');
Route::post('movie/store', ['as' => 'movie/store', 'uses' => 'MovieController@store']);
Route::get('movie/destroy/{id}', ['as' => 'movie/destroy', 'uses' => 'MovieController@destroy']);
Route::put('movie/update', ['as' => 'movie/update', 'uses' => 'MovieController@update']);
Route::post('movie/search', ['as' => 'movie/search', 'uses' => 'MovieController@search']);

// Rutas para categorias
Route::resource('category','CategoryController');
Route::get('category/destroy/{id}', ['as' => 'category/destroy', 'uses' => 'CategoryController@destroy']);
Route::post('category/show', ['as' => 'category/show', 'uses' => 'CategoryController@show']);
Route::post('category/store', ['as' => 'category/store', 'uses' => 'CategoryController@store']);
Route::put('category/update', ['as' => 'category/update', 'uses' => 'CategoryController@update']);
Route::post('category/search', ['as' => 'category/search', 'uses' => 'CategoryController@search']);

// Rutas para Usuarios
Route::resource('user','UserController');
Route::get('user/destroy/{id}', ['as' => 'user/destroy', 'uses' => 'UserController@destroy']);
Route::post('user/search', ['as' => 'user/search', 'uses' => 'UserController@search']);

// Rutas para Estados
Route::resource('state','StateController');
Route::get('state/destroy/{id}', ['as' => 'state/destroy', 'uses' => 'StateController@destroy']);
Route::post('state/search', ['as' => 'state/search', 'uses' => 'StateController@search']);

// Rutas para Excel "Carga masiva"
Route::post('/import-excel', ['as'=> 'import-excel', 'uses' => 'ExcelController@importMovies']);

?>

routes/user.php
<?php

//Rutas para peliculas
Route::get('movieList', ['as' => 'movieList', 'uses' => 'MovieController@list']);
?>

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/State.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class State extends Model
{
	protected $table = 'states';
	protected $fillable = ['state'];
	protected $guarded = ['id'];

	public function categories(){

		return $this->hasMany('App/Models/Category');
	}

	public function users()
    {
    	return $this->hasMany('App/User');
    }
    
    // hasmany: muchos
    public function movies()
    {
    	return $this->hasMany('App\Models\Movie');
    }
}

app/Http/Controllers/StateController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\State;

class StateController extends Controller
{
    public function index(){
    	$states = State::all();
    	return \View::make('states/list',compact('states'));
    }

    public function create(){
    	return \View::make('states/new');
    }

    public function store(Request $request){
    	$state = new State;
    	$state->state = $request->state;
    	$state->save();
    	return redirect('state');
    }

    public function edit($id){
        $state = State::find($id);
        return \View::make('states/update',compact('state'));
    }

    public function update($id, Request $request){
        $state = State::find($id);
        $state->state = $request->state;
        $state->save();
        return redirect('state');
    }

     public function search(Request $request){
        $states = State::where('state','like','%'.$request->state.'%')->get(); //busca por nombre similar
        $states = State::where('state','=',$request->state)->get();//busca por nombre igual
        return \View::make('states/list',compact('states'));
    }

    public function destroy($id) {
        $state = State::find($id);
        $state->delete();
        return redirect()->back();
    }
}

resources/views/states/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-12">
				{!! Form::open(['route' => 'state/search', 'method' => 'post', 'novalidate', 'class' => 'form-inline']) !!}
					<div class="form-group">
						<label>Estado</label>
						<input type="text" class="form-control" name="state">
					</div>
					<div class="form-control">
						<button type="submit" class="btn btn-default">Buscar</button>
						<a href="{{ route('state.index') }}" class="btn btn-primary">Todo</a>
						<a href="{{ route('state.create') }}" class="btn btn-primary">Crear</a>
					</div>	
				{!! Form::close() !!}
			</article>
			<article class="col-md-12">
				<table class="table table-condensed table-striped table-bordered">
					<thead>
						<tr>
							<th>Id</th>
							<th>Estado</th>
							<th>Acción</th>
						</tr>
					</thead>
					<tbody>
					<?php
					      require 'config.php';
					      $states = $collection->find([]);
					      foreach($states as $state) {
					         echo "<tr>";
					         echo "<td>".$state->state."</td>";
					         echo "<td>";
					         echo "</td>";
					         echo "</tr>";
					      };
					?>
							<a class="btn btn-primary btn-xs" href="{{ route('state.edit',['id' => $state->id]) }}">Editar</a>
							<a class="btn btn-danger btn-xs" href="{{ route('state/destroy',['id' => $state->id]) }}">Eliminar</a>
					</tbody>
				</table>
			</article>
		</div>
	</section>
@endsection

resources/views/states/new.blade.php
@extends('layouts.app')
@section('content')
<?php


session_start();


if(isset($_POST['submit'])){


   require 'config.php';


   $insertOneResult = $collection->insertOne([
       'state' => $_POST['state'],
   ]);


   $_SESSION['success'] = "Estado registrado exitosamente";
   header("Location: list.blade.php");
}
?>
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!! Form::open(['route' => 'state.store', 'method' => 'post', 'novalidate']) !!}
					<div class="form-group">
						<label>Estado</label>
						<input type="text" name="state" class="form-control" required>
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-success">Enviar</button>
					</div>
				{!! Form::close() !!}
			</article>
		</div>	
	</section>
@endsection

resources/views/states/update.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!! Form::model($state,['route' => ['state.update', $state->id], 'method' => 'put', 'novalidate']) !!}
					<div class="form-group">
						<label>Estado</label>
						<input type="text" name="state" class="form-control" required value="{{ $state->state }}">
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-success">Enviar</button>
					</div>
				{!! Form::close() !!}
			</article>
		</div>	
	</section>
@endsection