routes/admin.php
<?php
	
//Rutas para peliculas
Route::resource('movie','MovieController');
Route::post('movie/store', ['as' => 'movie/store', 'uses' => 'MovieController@store']);
Route::get('movie/destroy/{id}', ['as' => 'movie/destroy', 'uses' => 'MovieController@destroy']);
Route::put('movie/update', ['as' => 'movie/update', 'uses' => 'MovieController@update']);
Route::post('movie/search', ['as' => 'movie/search', 'uses' => 'MovieController@search']);

// Rutas para categorias
Route::resource('category','CategoryController');
Route::get('category/destroy/{id}', ['as' => 'category/destroy', 'uses' => 'CategoryController@destroy']);
Route::post('category/show', ['as' => 'category/show', 'uses' => 'CategoryController@show']);
Route::post('category/store', ['as' => 'category/store', 'uses' => 'CategoryController@store']);
Route::put('category/update', ['as' => 'category/update', 'uses' => 'CategoryController@update']);
Route::post('category/search', ['as' => 'category/search', 'uses' => 'CategoryController@search']);

// Rutas para Usuarios
Route::resource('user','UserController');
Route::get('user/destroy/{id}', ['as' => 'user/destroy', 'uses' => 'UserController@destroy']);
Route::post('user/search', ['as' => 'user/search', 'uses' => 'UserController@search']);

// Rutas para Estados
Route::resource('state','StateController');
Route::get('state/destroy/{id}', ['as' => 'state/destroy', 'uses' => 'StateController@destroy']);
Route::post('state/search', ['as' => 'state/search', 'uses' => 'StateController@search']);

// Rutas para Excel "Carga masiva"
Route::post('/import-excel', ['as'=> 'import-excel', 'uses' => 'ExcelController@importMovies']);

?>

routes/user.php
<?php

//Rutas para peliculas
Route::get('movieList', ['as' => 'movieList', 'uses' => 'MovieController@list']);
?>

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = "categories";
    protected $fillable = ['name','state_id'];
    protected $guarded = ['id'];    

    public function state()
    {
        return $this->belongsTo('App\Models\State');
    }
    
    //belongstomany: muchos a muchos
    public function movies()
    {
        return $this->belongsToMany('App\Models\Movie');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Category as Category;
use App\Models\State;

class CategoryController extends Controller
{
	public function index() {
        $categories = Category::all();
        return \View::make('categories/list',compact('categories'));
    }

    public function store(Request $request){
    	$category = new Category;
        $category->name = $request->name;
        $category->state_id = 1;        
        $category->save();
        return;
    }

    public function create(){
    	return \View::make('categories/new');
    }

    public function edit($id) {
        $category = Category::find($id);
        $states = State::select('id','state')->get();
        return \View::make('categories/update', compact('category','states'));
    }

    public function update($id, Request $request) {
        $category = Category::find($request->id);
        $category->name = $request->name;
        $category->state_id = $request->state;        
        $category->save();
        return;
    }

     public function search(Request $request){
        $categories = Category::where('name','like','%'.$request->name.'%')->get(); //busca por nombre similar
        $categories = Category::where('name','=',$request->name)->get();//busca por nombre igual
        return \View::make('categories/list',compact('categories'));
    }

    public function destroy($id){
        $category = Category::find($id);
        $category->delete();
        return redirect()->back();
    }

}

resources/views/categories/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-12">
				{!! Form::open(['route' => 'category/search', 'method' => 'post', 'novalidate', 'class' => 'form-inline']) !!}
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" class="form-control" name="name">
					</div>
					<div class="form-control">
						<button type="submit" class="btn btn-default">Buscar</button>
						<a href="{{ route('category.index') }}" class="btn btn-primary">Todo</a>
						<a href="{{ route('category.create') }}" class="btn btn-primary">Crear</a>
					</div>	
				{!! Form::close() !!}
			</article>
			<article class="col-md-12">
				<table class="table table-condensed table-striped table-bordered">
					<thead>
						<tr>
							<th>Nombre</th>
							<th>Estado</th>
							<th>Acción</th>
						</tr>
					</thead>
					<tbody>
						@foreach($categories as $category)
							<tr>
								<td>{{ $category->name }}</td>
								<td>{{ $category->state->state}}</td>
								<td>
									<a class="btn btn-primary btn-xs" href="{{ route('category.edit',['id' => $category->id]) }}">Editar</a>
									<a class="btn btn-danger btn-xs" href="{{ route('category/destroy',['id' => $category->id]) }}">Eliminar</a>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</article>
		</div>
	</section>
@endsection

resources/views/categories/new.blade.php
@extends('layouts.app')
@section('content')
	<new-category :edit="false" :category="null"></new-category>
@endsection

resources/views/categories/update.blade.php
@extends('layouts.app')
@section('content')
	<new-category :edit="true" :category="{{$category}}" :states="{{$states}}"></new-category>
@endsection